version: "3.8"
services:
  web:
    container_name: frs-web
    build: .
    command: uvicorn app.server:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    depends_on:
      - redis
    env_file: .env

  redis:
    container_name: frs-redis
    image: redis:6.0
    restart: always
    ports:
      - 6379:6379
    volumes:
      - frs-redis:/data

  worker:
    container_name: frs-worker
    build: .
    command: arq app.worker.WorkerSettings
    depends_on:
      - redis
      - web
    env_file: .env

  minio:
    container_name: frs-minio
    image: quay.io/minio/minio:RELEASE.2023-02-10T18-48-39Z
    command: minio server --console-address ":9090" /data
    ports:
      - 9000:9000
      - 9090:9090
    env_file: .env
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:9090/minio/health/live"]
    #   interval: 30s
    #   timeout: 20s
    #   retries: 3
    # volumes:
    #   - frs-minio:/data

volumes:
  frs-redis: null
  frs-minio: null