version: "3.8"
services:
  web:
    container_name: frs-web
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    depends_on:
      - redis
    env_file: .env

  redis:
    container_name: frs-redis
    image: redis:6.0
    restart: always
    ports:
      - 6379:6379
    volumes:
      - frs-redis:/data

  worker:
    container_name: frs-worker
    build: .
    command: arq app.worker.WorkerSettings
    depends_on:
      - redis
      - web
    env_file: .env


volumes:
  frs-redis: null